### ISSUE TITLE
pip install . isnt working, I googled the error returned with no help

### ISSUE THREAD

**Issue by Aakib03** [deepklarity/jupyter-text2code#10]
C:\Users\admin>pip install .
ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.

**Comment by dk-crazydiv** [comment]
Hi. Thanks for trying out. Your directory needs to be the folder which you downloaded/cloned `C:\Users\admin>` i.e. `jupyter-text2code>`. Windows currently isn't supported because we later found out that one underlying library we used is not available on pypi #2. We unfortunately do not have any windows machine to test this on, so I am afraid I cannot give you a timeframe for resolution, but we'll try our best to support windows as well.

**Comment by Aakib03** [comment]
Then on which operating system is this work on ?

**Comment by dk-crazydiv** [comment]
Ubuntu and Mac should work fine.

**Comment by JosephAlanLane** [comment]
Any resolution on this?

**Comment by dk-dsr** [comment]
Currently windows not supported. You can use our docker images to use the extension.
