### ISSUE TITLE
404 error while using the jupyter extension

### ISSUE THREAD

**Issue by vj-python** [deepklarity/jupyter-text2code#15]
Hitting Mopp it in the Jupyter extension throws 404 errors.

404 GET /mopp?query=import%20all%20libraries&dataframes_info=%27%7B%7D%27 (127.0.0.1)

**Comment by dk-crazydiv** [comment]
Could you please provide more info on your OS and also some logs of when you start `jupyter notebook`. This error happens when server extension isn't loaded. It could be related to #14, and in the meantime you could manually workaround the error using steps here: #8. Looking at `jupyter notebook` logs will should be a good start.

**Comment by dk-dsr** [comment]
Closing due to no response.
